trigger:
  - main

pool:
  name: KarateDL


jobs:
  - job: Stage1
    displayName: 'Run Karate Tests for Stage 1'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test -Dkarate.options="--tags @stage1"'
        displayName: 'Run Stage 1 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports'
          artifact: 'Karate Test Results Stage 1'

  - job: Stage2
    displayName: 'Run Karate Tests for Stage 2'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test -Dkarate.options="--tags @stage2"'
        displayName: 'Run Stage 2 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports'
          artifact: 'Karate Test Results Stage 2'

  - job: Stage3
    displayName: 'Run Karate Tests for Stage 3'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test -Dkarate.options="--tags @stage3"'
        displayName: 'Run Stage 3 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports'
          artifact: 'Karate Test Results Stage 3'