trigger:
  - main

pool:
  name: KarateDL

steps:
  - task: Gradle@4
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/build/test-results/test/*.xml'
    displayName: 'Run Karate Tests'


  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build/karate-reports/karate-reports/'
      ArtifactName: 'Karate Test Results'
      publishLocation: 'Container'

  - script: echo "Karate tests executed successfully"
    displayName: 'Log Test Execution'