trigger:
  - main

pool:
  name: KarateDL

jobs:
  - job: Stage1
    displayName: 'Run Karate Tests for Stage 1'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage1"'
        displayName: 'Run Stage 1 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 1'

  - job: Stage2
    displayName: 'Run Karate Tests for Stage 2'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage2"'
        displayName: 'Run Stage 2 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 2'

  - job: Stage3
    displayName: 'Run Karate Tests for Stage 3'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage3"'
        displayName: 'Run Stage 3 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 3'

  - job: Stage4
    displayName: 'Run Karate Tests for Stage 4'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage2"'
        displayName: 'Run Stage 4 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 4'

  - job: Stage5
    displayName: 'Run Karate Tests for Stage 5'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage1"'
        displayName: 'Run Stage 5 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 5'

  - job: Stage6
    displayName: 'Run Karate Tests for Stage 6'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage3"'
        displayName: 'Run Stage 6 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 6'

  - job: Stage7
    displayName: 'Run Karate Tests for Stage 7'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage1"'
        displayName: 'Run Stage 7 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 7'

  - job: Stage8
    displayName: 'Run Karate Tests for Stage 8'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage2"'
        displayName: 'Run Stage 8 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 8'                    

  - job: Stage9
    displayName: 'Run Karate Tests for Stage 9'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage1"'
        displayName: 'Run Stage 9 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 9'                    

  - job: Stage10
    displayName: 'Run Karate Tests for Stage 10'
    steps:
      - task: Gradle@4
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'test'
          options: '-Dkarate.options="--tags @stage3"'
        displayName: 'Run Stage 8 Tests'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'build/karate-reports/karate-reports'
          artifact: 'Karate Test Results Stage 10'                    
